// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa_cD1WUvc7B1hbH6sh1WJyJWgG60QviQ',
    appId: '1:515866796689:web:bdd4c8d6370517fa571530',
    messagingSenderId: '515866796689',
    projectId: 'healthcare-flutter-project',
    authDomain: 'healthcare-flutter-project.firebaseapp.com',
    storageBucket: 'healthcare-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9hJ2_0jBoAgOy16TOGvNoyHvIgnXa76Y',
    appId: '1:515866796689:android:8e7cb983852d7b45571530',
    messagingSenderId: '515866796689',
    projectId: 'healthcare-flutter-project',
    storageBucket: 'healthcare-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY6DyYQElh5kD21-pUceXTmD26CrFjbbw',
    appId: '1:515866796689:ios:d203f7832b371cd2571530',
    messagingSenderId: '515866796689',
    projectId: 'healthcare-flutter-project',
    storageBucket: 'healthcare-flutter-project.appspot.com',
    iosClientId: '515866796689-fi8dbcc8j9to74q7p9c7jar2emc3vg23.apps.googleusercontent.com',
    iosBundleId: 'com.health.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY6DyYQElh5kD21-pUceXTmD26CrFjbbw',
    appId: '1:515866796689:ios:f68176fe13ae8509571530',
    messagingSenderId: '515866796689',
    projectId: 'healthcare-flutter-project',
    storageBucket: 'healthcare-flutter-project.appspot.com',
    iosClientId: '515866796689-ao7jo1lamnqgj1619l39enka7ff5r3k5.apps.googleusercontent.com',
    iosBundleId: 'com.health.healthcare.RunnerTests',
  );
}
